global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'query-service'
    static_configs:
      - targets: ['query-service:8080']
  
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
  
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:9363']

